export const geschichteCardValues = {
    grundschule: {
      easy: [
        { id: "ge001", set1: "Von wann bis wann war der Zweite Weltkrieg?", set2: "1939 bis 1945" },
        { id: "ge002", set1: "Wann wurde die Berliner Mauer gebaut?", set2: "1961" },
        { id: "ge003", set1: "Wer entdeckte Amerika?", set2: "Christoph Kolumbus" },
        { id: "ge004", set1: "Wann war die Französische Revolution?", set2: "1789" },
        { id: "ge005", set1: "Wann wurde Deutschland wiedervereint?", set2: "1990" },
        { id: "ge006", set1: "Wann landeten die ersten Menschen auf dem Mond?", set2: "1969" },
        { id: "ge007", set1: "Wie hieß der erste Bundeskanzler der Bundesrepublik Deutschland?", set2: "Konrad Adenauer" },
        { id: "ge008", set1: "In welchem Jahr begann der Erste Weltkrieg?", set2: "1914" },
        { id: "ge009", set1: "Wann wurde die Europäische Union gegründet?", set2: "1993" },
        { id: "ge010", set1: "Wie lange dauerte der Zweite Weltkrieg?", set2: "6 Jahre" },
        { id: "ge011", set1: "Wer war der erste Präsident der Vereinigten Staaten?", set2: "George Washington" },
        { id: "ge012", set1: "Wann begann die Industrialisierung?", set2: "Im 18. Jahrhundert" },
        { id: "ge013", set1: "Wer war der berühmteste Pharao des alten Ägyptens?", set2: "Tutanchamun" },
        { id: "ge014", set1: "Wann wurde das Deutsche Kaiserreich gegründet?", set2: "1871" },
        { id: "ge015", set1: "Wer schrieb die 95 Thesen gegen den Ablasshandel?", set2: "Martin Luther" },
        { id: "ge016", set1: "Wer war der erste Mensch im Weltall?", set2: "Juri Gagarin" },
        { id: "ge017", set1: "Wann endete die DDR?", set2: "1990" },
        { id: "ge018", set1: "Welches Jahr markiert den Untergang der Titanic?", set2: "1912" },
        { id: "ge019", set1: "In welchem Jahr wurde das Grundgesetz der Bundesrepublik Deutschland verabschiedet?", set2: "1949" },
        { id: "ge020", set1: "Wann wurde die UNO gegründet?", set2: "1945" } 
      ],
      normal: [
        { id: "gn001", set1: "Wann endete der Erste Weltkrieg?", set2: "1918" },
        { id: "gn002", set1: "Wie lange dauerte der Dreißigjährige Krieg?", set2: "30 Jahre (1618 bis 1648)" },
        { id: "gn003", set1: "Wann wurde das Römische Reich gegründet?", set2: "27 v. Chr." },
        { id: "gn004", set1: "Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?", set2: "Konrad Adenauer" },
        { id: "gn005", set1: "Wann fand der Westfälische Frieden statt?", set2: "1648" },
        { id: "gn006", set1: "Wann wurde die Berliner Mauer abgerissen?", set2: "1989" },
        { id: "gn007", set1: "Wer führte die französischen Truppen bei der Schlacht von Waterloo?", set2: "Napoleon Bonaparte" },
        { id: "gn008", set1: "Welcher König wurde 1066 bei der Schlacht von Hastings besiegt?", set2: "Harold II." },
        { id: "gn009", set1: "Wann wurde der Vertrag von Versailles unterzeichnet?", set2: "1919" },
        { id: "gn010", set1: "Wie lange dauerte die Weimarer Republik?", set2: "14 Jahre (1919 bis 1933)" },
        { id: "gn011", set1: "Wer war der erste Präsident der Weimarer Republik?", set2: "Friedrich Ebert" },
        { id: "gn012", set1: "In welchem Jahr wurde die Magna Carta unterzeichnet?", set2: "1215" },
        { id: "gn013", set1: "Wann begann der Kalte Krieg?", set2: "1947" },
        { id: "gn014", set1: "Wann endete das Römische Reich im Westen?", set2: "476 n. Chr." },
        { id: "gn015", set1: "Wer war der Führer der Nationalsozialisten in Deutschland?", set2: "Adolf Hitler" },
        { id: "gn016", set1: "Wer war der Hauptautor der Unabhängigkeitserklärung der USA?", set2: "Thomas Jefferson" },
        { id: "gn017", set1: "Wann begann der Zweite Weltkrieg in Europa?", set2: "1939" },
        { id: "gn018", set1: "Wie lange dauerte der Hundertjährige Krieg?", set2: "116 Jahre (1337 bis 1453)" },
        { id: "gn019", set1: "Wer führte die Armee der Spartaner in der Schlacht bei den Thermopylen?", set2: "König Leonidas" },
        { id: "gn020", set1: "Wann wurde das Deutsche Reich gegründet?", set2: "1871" }
      ],
      hard: [
        { id: "gh001", set1: "Wer war der Kaiser des Heiligen Römischen Reiches im Jahr 800?", set2: "Karl der Große" },
        { id: "gh002", set1: "Wann begann die Französische Revolution?", set2: "1789" },
        { id: "gh003", set1: "Wer war der erste römische Kaiser?", set2: "Augustus" },
        { id: "gh004", set1: "Wann fand der Westfälische Frieden statt?", set2: "1648" },
        { id: "gh005", set1: "Wer war der Begründer des Islam?", set2: "Prophet Mohammed" },
        { id: "gh006", set1: "Welches Land regierte Elisabeth I.?", set2: "England" },
        { id: "gh007", set1: "Wie hieß die Hauptstadt des Byzantinischen Reiches?", set2: "Konstantinopel" },
        { id: "gh008", set1: "Wer führte Hannibal während des Zweiten Punischen Krieges an?", set2: "Die Karthager" },
        { id: "gh009", set1: "In welchem Jahr begann die Völkerwanderung?", set2: "376 n. Chr." },
        { id: "gh010", set1: "Wann wurde der Wiener Kongress abgehalten?", set2: "1814 bis 1815" },
        { id: "gh011", set1: "Wie hieß der letzte russische Zar?", set2: "Nikolaus II." },
        { id: "gh012", set1: "Wann wurde die Atombombe auf Hiroshima abgeworfen?", set2: "1945" },
        { id: "gh013", set1: "Wer war der Premierminister von Großbritannien während des Zweiten Weltkriegs?", set2: "Winston Churchill" },
        { id: "gh014", set1: "Wie lange dauerte der Peloponnesische Krieg?", set2: "27 Jahre (431 bis 404 v. Chr.)" },
        { id: "gh015", set1: "Wann fand der amerikanische Bürgerkrieg statt?", set2: "1861 bis 1865" },
        { id: "gh016", set1: "Wer schrieb 'Das Kapital'?", set2: "Karl Marx" },
        { id: "gh017", set1: "Wann wurde die Sowjetunion gegründet?", set2: "1922" },
        { id: "gh018", set1: "Wer führte die Reformation 1517 an?", set2: "Martin Luther" },
        { id: "gh019", set1: "Wer war der Führer der Hunnen?", set2: "Attila" },
        { id: "gh020", set1: "Wann endete das Byzantinische Reich?", set2: "1453" } 
      ],
    },
    hauptschule: {
      easy: [
        { id: "he001", set1: "Von wann bis wann war der Zweite Weltkrieg?", set2: "1939 bis 1945" },
        { id: "he002", set1: "Wann wurde die Berliner Mauer gebaut?", set2: "1961" },
        { id: "he003", set1: "Wann wurde die Berliner Mauer abgerissen?", set2: "1989" },
        { id: "he004", set1: "Wann war die Französische Revolution?", set2: "1789" },
        { id: "he005", set1: "Wann wurde Deutschland wiedervereint?", set2: "1990" },
        { id: "he006", set1: "Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?", set2: "Konrad Adenauer" },
        { id: "he007", set1: "Wer entdeckte Amerika?", set2: "Christoph Kolumbus" },
        { id: "he008", set1: "In welchem Jahr begann der Erste Weltkrieg?", set2: "1914" },
        { id: "he009", set1: "Wie lange dauerte der Zweite Weltkrieg?", set2: "6 Jahre" },
        { id: "he010", set1: "Wann landeten die ersten Menschen auf dem Mond?", set2: "1969" },
        { id: "he011", set1: "Wann begann die Industrialisierung?", set2: "Im 18. Jahrhundert" },
        { id: "he012", set1: "Wann wurde die UNO gegründet?", set2: "1945" },
        { id: "he013", set1: "Wann wurde die Europäische Union gegründet?", set2: "1993" },
        { id: "he014", set1: "Wer war der erste Präsident der Vereinigten Staaten?", set2: "George Washington" },
        { id: "he015", set1: "Wann wurde das Deutsche Kaiserreich gegründet?", set2: "1871" },
        { id: "he016", set1: "Wann endete die DDR?", set2: "1990" },
        { id: "he017", set1: "In welchem Jahr sank die Titanic?", set2: "1912" },
        { id: "he018", set1: "Wer war der Führer der Nationalsozialisten in Deutschland?", set2: "Adolf Hitler" },
        { id: "he019", set1: "Wann wurde das Grundgesetz der Bundesrepublik Deutschland verabschiedet?", set2: "1949" },
        { id: "he020", set1: "Wann begann der Kalte Krieg?", set2: "1947" } 
      ],
      normal: [
        { id: "hn001", set1: "Wann endete der Erste Weltkrieg?", set2: "1918" },
        { id: "hn002", set1: "Wie lange dauerte der Dreißigjährige Krieg?", set2: "30 Jahre (1618 bis 1648)" },
        { id: "hn003", set1: "Wann wurde das Römische Reich gegründet?", set2: "27 v. Chr." },
        { id: "hn004", set1: "Wer war der erste Präsident der Weimarer Republik?", set2: "Friedrich Ebert" },
        { id: "hn005", set1: "Wann fand der Westfälische Frieden statt?", set2: "1648" },
        { id: "hn006", set1: "Wer war der Hauptautor der Unabhängigkeitserklärung der USA?", set2: "Thomas Jefferson" },
        { id: "hn007", set1: "Wann begann die Französische Revolution?", set2: "1789" },
        { id: "hn008", set1: "Wie lange dauerte die Weimarer Republik?", set2: "14 Jahre (1919 bis 1933)" },
        { id: "hn009", set1: "Wann wurde die Berliner Mauer errichtet?", set2: "1961" },
        { id: "hn010", set1: "Wann begann der Zweite Weltkrieg?", set2: "1939" },
        { id: "hn011", set1: "Wann wurde der Vertrag von Versailles unterzeichnet?", set2: "1919" },
        { id: "hn012", set1: "Wer war der Premierminister von Großbritannien während des Zweiten Weltkriegs?", set2: "Winston Churchill" },
        { id: "hn013", set1: "Wann wurde das Deutsche Kaiserreich gegründet?", set2: "1871" },
        { id: "hn014", set1: "Wann wurde die Atombombe auf Hiroshima abgeworfen?", set2: "1945" },
        { id: "hn015", set1: "Wie lange dauerte der Hundertjährige Krieg?", set2: "116 Jahre (1337 bis 1453)" },
        { id: "hn016", set1: "Wer führte die Reformation im Jahr 1517 an?", set2: "Martin Luther" },
        { id: "hn017", set1: "Wann endete der Kalte Krieg?", set2: "1991" },
        { id: "hn018", set1: "Wann wurde die Sowjetunion gegründet?", set2: "1922" },
        { id: "hn019", set1: "Wer war der Führer der Hunnen?", set2: "Attila" },
        { id: "hn020", set1: "Wann wurde die Magna Carta unterzeichnet?", set2: "1215" } 
      ],
      hard: [
        { id: "hh001", set1: "Wer war Kaiser des Heiligen Römischen Reiches im Jahr 800?", set2: "Karl der Große" },
        { id: "hh002", set1: "Wann wurde das Römische Reich aufgeteilt?", set2: "395 n. Chr." },
        { id: "hh003", set1: "Wie hieß die Hauptstadt des Byzantinischen Reiches?", set2: "Konstantinopel" },
        { id: "hh004", set1: "Wann fand die Schlacht von Hastings statt?", set2: "1066" },
        { id: "hh005", set1: "Wann begann die Völkerwanderung?", set2: "376 n. Chr." },
        { id: "hh006", set1: "Wie lange dauerte der Peloponnesische Krieg?", set2: "27 Jahre (431 bis 404 v. Chr.)" },
        { id: "hh007", set1: "Wer war der letzte Zar von Russland?", set2: "Nikolaus II." },
        { id: "hh008", set1: "Wann begann die Französische Revolution?", set2: "1789" },
        { id: "hh009", set1: "Wer war der Führer der Karthager im Zweiten Punischen Krieg?", set2: "Hannibal" },
        { id: "hh010", set1: "Wann fand der Wiener Kongress statt?", set2: "1814 bis 1815" },
        { id: "hh011", set1: "Wann begann der amerikanische Bürgerkrieg?", set2: "1861" },
        { id: "hh012", set1: "Wann endete das Byzantinische Reich?", set2: "1453" },
        { id: "hh013", set1: "Wann wurde die Atombombe auf Nagasaki abgeworfen?", set2: "1945" },
        { id: "hh014", set1: "Wann fand die Oktoberrevolution in Russland statt?", set2: "1917" },
        { id: "hh015", set1: "Wann wurde die NATO gegründet?", set2: "1949" },
        { id: "hh016", set1: "Wann begann die Industrialisierung in Deutschland?", set2: "Um 1830" },
        { id: "hh017", set1: "Wann wurde die Berliner Blockade aufgehoben?", set2: "1949" },
        { id: "hh018", set1: "Wann wurde die erste deutsche Eisenbahn eröffnet?", set2: "1835" },
        { id: "hh019", set1: "Wer führte die Truppen bei der Schlacht von Waterloo an?", set2: "Napoleon Bonaparte" },
        { id: "hh020", set1: "Wann wurde das Heilige Römische Reich aufgelöst?", set2: "1806" }
      ],
    },
    realschule: {
      easy: [
        { id: "re001", set1: "Von wann bis wann war der Zweite Weltkrieg?", set2: "1939 bis 1945" },
        { id: "re002", set1: "Wann wurde die Berliner Mauer gebaut?", set2: "1961" },
        { id: "re003", set1: "Wann wurde die Berliner Mauer abgerissen?", set2: "1989" },
        { id: "re004", set1: "Wann wurde Deutschland wiedervereint?", set2: "1990" },
        { id: "re005", set1: "Wann war die Französische Revolution?", set2: "1789" },
        { id: "re006", set1: "Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?", set2: "Konrad Adenauer" },
        { id: "re007", set1: "Wer entdeckte Amerika?", set2: "Christoph Kolumbus" },
        { id: "re008", set1: "In welchem Jahr begann der Erste Weltkrieg?", set2: "1914" },
        { id: "re009", set1: "Wie lange dauerte der Zweite Weltkrieg?", set2: "6 Jahre" },
        { id: "re010", set1: "Wann landeten die ersten Menschen auf dem Mond?", set2: "1969" },
        { id: "re011", set1: "Wann wurde die UNO gegründet?", set2: "1945" },
        { id: "re012", set1: "Wann wurde die Europäische Union gegründet?", set2: "1993" },
        { id: "re013", set1: "Wer war der erste Präsident der Vereinigten Staaten?", set2: "George Washington" },
        { id: "re014", set1: "Wann wurde das Deutsche Kaiserreich gegründet?", set2: "1871" },
        { id: "re015", set1: "Wann endete die DDR?", set2: "1990" },
        { id: "re016", set1: "In welchem Jahr sank die Titanic?", set2: "1912" },
        { id: "re017", set1: "Wann wurde das Grundgesetz der Bundesrepublik Deutschland verabschiedet?", set2: "1949" },
        { id: "re018", set1: "Wann begann der Kalte Krieg?", set2: "1947" },
        { id: "re019", set1: "Wann endete der Erste Weltkrieg?", set2: "1918" },
        { id: "re020", set1: "Wer war der Führer der Nationalsozialisten in Deutschland?", set2: "Adolf Hitler" } 
      ],
      normal: [
        { id: "rn001", set1: "Wann endete der Erste Weltkrieg?", set2: "1918" },
        { id: "rn002", set1: "Wie lange dauerte der Dreißigjährige Krieg?", set2: "30 Jahre (1618 bis 1648)" },
        { id: "rn003", set1: "Wann wurde das Römische Reich gegründet?", set2: "27 v. Chr." },
        { id: "rn004", set1: "Wer war der erste Präsident der Weimarer Republik?", set2: "Friedrich Ebert" },
        { id: "rn005", set1: "Wann fand der Westfälische Frieden statt?", set2: "1648" },
        { id: "rn006", set1: "Wer war der Hauptautor der Unabhängigkeitserklärung der USA?", set2: "Thomas Jefferson" },
        { id: "rn007", set1: "Wann begann die Französische Revolution?", set2: "1789" },
        { id: "rn008", set1: "Wie lange dauerte die Weimarer Republik?", set2: "14 Jahre (1919 bis 1933)" },
        { id: "rn009", set1: "Wann wurde die Berliner Mauer errichtet?", set2: "1961" },
        { id: "rn010", set1: "Wann begann der Zweite Weltkrieg?", set2: "1939" },
        { id: "rn011", set1: "Wann wurde der Vertrag von Versailles unterzeichnet?", set2: "1919" },
        { id: "rn012", set1: "Wer war der Premierminister von Großbritannien während des Zweiten Weltkriegs?", set2: "Winston Churchill" },
        { id: "rn013", set1: "Wann wurde das Deutsche Kaiserreich gegründet?", set2: "1871" },
        { id: "rn014", set1: "Wann wurde die Atombombe auf Hiroshima abgeworfen?", set2: "1945" },
        { id: "rn015", set1: "Wie lange dauerte der Hundertjährige Krieg?", set2: "116 Jahre (1337 bis 1453)" },
        { id: "rn016", set1: "Wer führte die Reformation im Jahr 1517 an?", set2: "Martin Luther" },
        { id: "rn017", set1: "Wann endete der Kalte Krieg?", set2: "1991" },
        { id: "rn018", set1: "Wann wurde die Sowjetunion gegründet?", set2: "1922" },
        { id: "rn019", set1: "Wer war der Führer der Hunnen?", set2: "Attila" },
        { id: "rn020", set1: "Wann wurde die Magna Carta unterzeichnet?", set2: "1215" }
      ],
      hard: [
        { id: "rh001", set1: "Wer war der Kaiser des Heiligen Römischen Reiches im Jahr 800?", set2: "Karl der Große" },
        { id: "rh002", set1: "Wann wurde das Römische Reich aufgeteilt?", set2: "395 n. Chr." },
        { id: "rh003", set1: "Wie hieß die Hauptstadt des Byzantinischen Reiches?", set2: "Konstantinopel" },
        { id: "rh004", set1: "Wann fand die Schlacht von Hastings statt?", set2: "1066" },
        { id: "rh005", set1: "Wann begann die Völkerwanderung?", set2: "376 n. Chr." },
        { id: "rh006", set1: "Wie lange dauerte der Peloponnesische Krieg?", set2: "27 Jahre (431 bis 404 v. Chr.)" },
        { id: "rh007", set1: "Wer war der letzte Zar von Russland?", set2: "Nikolaus II." },
        { id: "rh008", set1: "Wann wurde die Atombombe auf Nagasaki abgeworfen?", set2: "1945" },
        { id: "rh009", set1: "Wer führte Hannibal während des Zweiten Punischen Krieges an?", set2: "Die Karthager" },
        { id: "rh010", set1: "Wann wurde der Wiener Kongress abgehalten?", set2: "1814 bis 1815" },
        { id: "rh011", set1: "Wer war der Führer der Karthager im Zweiten Punischen Krieg?", set2: "Hannibal" },
        { id: "rh012", set1: "Wann endete das Byzantinische Reich?", set2: "1453" },
        { id: "rh013", set1: "Wie hieß die Reformbewegung, die Martin Luther 1517 einleitete?", set2: "Reformation" },
        { id: "rh014", set1: "Wann fand die Oktoberrevolution in Russland statt?", set2: "1917" },
        { id: "rh015", set1: "Wann wurde die NATO gegründet?", set2: "1949" },
        { id: "rh016", set1: "Wann begann die Industrialisierung in Deutschland?", set2: "Um 1830" },
        { id: "rh017", set1: "Wann wurde die Berliner Blockade aufgehoben?", set2: "1949" },
        { id: "rh018", set1: "Wann wurde die erste deutsche Eisenbahn eröffnet?", set2: "1835" },
        { id: "rh019", set1: "Wer führte die Truppen bei der Schlacht von Waterloo an?", set2: "Napoleon Bonaparte" },
        { id: "rh020", set1: "Wann wurde das Heilige Römische Reich aufgelöst?", set2: "1806" } 
      ],
    },
    gymnasium: {
      easy: [
        { id: "ge001", set1: "Von wann bis wann war der Zweite Weltkrieg?", set2: "1939 bis 1945" },
        { id: "ge002", set1: "Wann wurde die Berliner Mauer gebaut?", set2: "1961" },
        { id: "ge003", set1: "Wann wurde die Berliner Mauer abgerissen?", set2: "1989" },
        { id: "ge004", set1: "Wann wurde Deutschland wiedervereint?", set2: "1990" },
        { id: "ge005", set1: "Wann war die Französische Revolution?", set2: "1789" },
        { id: "ge006", set1: "Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?", set2: "Konrad Adenauer" },
        { id: "ge007", set1: "Wer entdeckte Amerika?", set2: "Christoph Kolumbus" },
        { id: "ge008", set1: "In welchem Jahr begann der Erste Weltkrieg?", set2: "1914" },
        { id: "ge009", set1: "Wie lange dauerte der Zweite Weltkrieg?", set2: "6 Jahre" },
        { id: "ge010", set1: "Wann landeten die ersten Menschen auf dem Mond?", set2: "1969" },
        { id: "ge011", set1: "Wann wurde die UNO gegründet?", set2: "1945" },
        { id: "ge012", set1: "Wann wurde die Europäische Union gegründet?", set2: "1993" },
        { id: "ge013", set1: "Wer war der erste Präsident der Vereinigten Staaten?", set2: "George Washington" },
        { id: "ge014", set1: "Wann wurde das Deutsche Kaiserreich gegründet?", set2: "1871" },
        { id: "ge015", set1: "Wann endete die DDR?", set2: "1990" },
        { id: "ge016", set1: "In welchem Jahr sank die Titanic?", set2: "1912" },
        { id: "ge017", set1: "Wann wurde das Grundgesetz der Bundesrepublik Deutschland verabschiedet?", set2: "1949" },
        { id: "ge018", set1: "Wann begann der Kalte Krieg?", set2: "1947" },
        { id: "ge019", set1: "Wann endete der Erste Weltkrieg?", set2: "1918" },
        { id: "ge020", set1: "Wer war der Führer der Nationalsozialisten in Deutschland?", set2: "Adolf Hitler" } 
      ],
      normal: [
        { id: "gn001", set1: "Wann endete der Erste Weltkrieg?", set2: "1918" },
        { id: "gn002", set1: "Wie lange dauerte der Dreißigjährige Krieg?", set2: "30 Jahre (1618 bis 1648)" },
        { id: "gn003", set1: "Wann wurde das Römische Reich gegründet?", set2: "27 v. Chr." },
        { id: "gn004", set1: "Wer war der erste Präsident der Weimarer Republik?", set2: "Friedrich Ebert" },
        { id: "gn005", set1: "Wann fand der Westfälische Frieden statt?", set2: "1648" },
        { id: "gn006", set1: "Wer war der Hauptautor der Unabhängigkeitserklärung der USA?", set2: "Thomas Jefferson" },
        { id: "gn007", set1: "Wann begann die Französische Revolution?", set2: "1789" },
        { id: "gn008", set1: "Wie lange dauerte die Weimarer Republik?", set2: "14 Jahre (1919 bis 1933)" },
        { id: "gn009", set1: "Wann wurde die Berliner Mauer errichtet?", set2: "1961" },
        { id: "gn010", set1: "Wann begann der Zweite Weltkrieg?", set2: "1939" },
        { id: "gn011", set1: "Wann wurde der Vertrag von Versailles unterzeichnet?", set2: "1919" },
        { id: "gn012", set1: "Wer war der Premierminister von Großbritannien während des Zweiten Weltkriegs?", set2: "Winston Churchill" },
        { id: "gn013", set1: "Wann wurde das Deutsche Kaiserreich gegründet?", set2: "1871" },
        { id: "gn014", set1: "Wann wurde die Atombombe auf Hiroshima abgeworfen?", set2: "1945" },
        { id: "gn015", set1: "Wie lange dauerte der Hundertjährige Krieg?", set2: "116 Jahre (1337 bis 1453)" },
        { id: "gn016", set1: "Wer führte die Reformation im Jahr 1517 an?", set2: "Martin Luther" },
        { id: "gn017", set1: "Wann endete der Kalte Krieg?", set2: "1991" },
        { id: "gn018", set1: "Wann wurde die Sowjetunion gegründet?", set2: "1922" },
        { id: "gn019", set1: "Wer war der Führer der Hunnen?", set2: "Attila" },
        { id: "gn020", set1: "Wann wurde die Magna Carta unterzeichnet?", set2: "1215" } 
      ],
      hard: [
        { id: "gh001", set1: "Wer war Kaiser des Heiligen Römischen Reiches im Jahr 800?", set2: "Karl der Große" },
        { id: "gh002", set1: "Wann wurde das Römische Reich aufgeteilt?", set2: "395 n. Chr." },
        { id: "gh003", set1: "Wie hieß die Hauptstadt des Byzantinischen Reiches?", set2: "Konstantinopel" },
        { id: "gh004", set1: "Wann fand die Schlacht von Hastings statt?", set2: "1066" },
        { id: "gh005", set1: "Wann begann die Völkerwanderung?", set2: "376 n. Chr." },
        { id: "gh006", set1: "Wie lange dauerte der Peloponnesische Krieg?", set2: "27 Jahre (431 bis 404 v. Chr.)" },
        { id: "gh007", set1: "Wer war der letzte Zar von Russland?", set2: "Nikolaus II." },
        { id: "gh008", set1: "Wann wurde die Atombombe auf Nagasaki abgeworfen?", set2: "1945" },
        { id: "gh009", set1: "Wer führte die Karthager im Zweiten Punischen Krieg an?", set2: "Hannibal" },
        { id: "gh010", set1: "Wann fand der Wiener Kongress statt?", set2: "1814 bis 1815" },
        { id: "gh011", set1: "Wann wurde die NATO gegründet?", set2: "1949" },
        { id: "gh012", set1: "Wann endete das Byzantinische Reich?", set2: "1453" },
        { id: "gh013", set1: "Wie hieß die Reformbewegung, die Martin Luther 1517 einleitete?", set2: "Reformation" },
        { id: "gh014", set1: "Wann fand die Oktoberrevolution in Russland statt?", set2: "1917" },
        { id: "gh015", set1: "Wann wurde die erste deutsche Eisenbahn eröffnet?", set2: "1835" },
        { id: "gh016", set1: "Wer führte die Truppen bei der Schlacht von Waterloo an?", set2: "Napoleon Bonaparte" },
        { id: "gh017", set1: "Wann wurde das Heilige Römische Reich aufgelöst?", set2: "1806" },
        { id: "gh018", set1: "Wann wurde der Westfälische Frieden unterzeichnet?", set2: "1648" },
        { id: "gh019", set1: "Wann wurde die Sowjetunion gegründet?", set2: "1922" },
        { id: "gh020", set1: "Wer war der Gründer der Qin-Dynastie in China?", set2: "Qin Shi Huangdi" } 
      ],
    },
  };